server:
  port: 9999
spring:
  application:
    name: admin_demo_spring
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        # show_sql: true
        default_batch_fetch_size: 1000
  datasource:
    url: jdbc:postgresql://localhost:5501/XPRODB
    username: XADMIN
    password: XADMIN
    driver-class-name: org.postgresql.Driver


